name: Creando-usando Artefacts
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  creando-artifact:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurando JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Dar permisos a mvnw
        run: chmod +x mvnw
      - name: Compilando el *.jar
        run: ./mvnw clean package -DskipTests
        env:
          SPRING_PROFILES_ACTIVE: dev
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: Subir JAR a workflow artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: springboot-app
          path: target/*.jar